---
title: "practice0325"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Atomic Vector

```{r}
num1 <- 5
vNum1 <- c(2,5)
vNum2 <- c(2, num1) #右邊num1是在call num1 所以相當於c(2,5)
```

```{r}
num1 <- 5
num2 <- c(5) #只有一個向量的時候不用加c
```
向量的堆疊依然是向量
```{r}
vNum1 <- c(-1,5)
vNum2 <- c(2,3)
vNum3 <- c(vNum1,vNum2)
vNum4 <- c(-1,5,2,3)
vNum5 <- c(c(-1,5),c(2,3)) #實際上是輸入第26或27行的結果
```

```{r}
vNumComplex <- c(c(1,3,c(-5,23)))
vNumcomplexnotcomplexAtAll <- c(1,3,-5,23) #兩個是一樣的
```

Vector stacking 向量堆疊
```{r}
vNum1 <- c(-1,5)
vNum2 <- c(2,3)
vNum4 <- c() # 空向量
```

```{r}
vNum3 <- c(vNum2, vNum1)
vNum4 <- c(vNum4, vNum1) # 向量疊代 （recursive vector concatenate）
#如果重複run,vNum4會一直重新被定義:empty > -1,5 > -1,5,-1,5
```

##Numeric
```{r}
num1<-5 # 非整數，電腦會記成5.00000
num2<-5L # 整數

num1Vector<-c(5,6,7)
num2Vector<-c(5L,6L,7L)
```

```{r}
typeof(num1Vector)
typeof(num2Vector)
```

##Character

```{r}
char1<-"你好"
char2<-'你好'
```

```{r}
char1Vector<-c("你好","How are you?")
```

###Atomic精神
```{r}
complexVector <- c("小明今年歲數","15")
```

```{r}
class(char1)
class(char2)
class(char1Vector)
```

他說："今天多了一個確診"
```{r}
HeSaid <- '他說:"今天多了一個確診"' #外面只能用單引號 不能用雙引 否則會出現兩組雙引號
```
```{r}
library(httr)
library(dplyr)
GET("https://api.github.com/repos/tpemartin/108-2-56-inclass-practice/commits") %>%
  content() %>%
  View()
```

```{r}
library(googlesheets4)
`出席狀況表單網址` <- "https://docs.google.com/spreadsheets/d/1EAG49qDKPWWi0ebkVr29TLrvVnoBPfkvxYY-J3xLAHY/edit#gid=458686645" # 缺乏定義值
ss <- as_sheets_id(`出席狀況表單網址`)
homework_sheet <- sheets_read(ss,sheet=1)
```

##Logic

```{r}
logi1 <- c(T,TRUE,F,FALSE,FALSE)
```

```{r}
# 加總向量內的所有元素值。
sum(logi1)
```

###Atomic Vector Extended

```{r}
# 10位學生的主系
majors10_char <- c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')

typeof(majors10_char)
class(majors10_char)
```

```{r}
majors10_factor <- factor(majors10_char)
# 或
majors10_factor <- factor(
  c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')
)

typeof(majors10_factor)
class(majors10_factor)
```

```{r}
levels(majors10_factor)
```






