---
title: "0403practice"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## List
```{r}
vectorExample <- c(2,6,7) #之前教的
listExample <- list(2,6,7) #新的list 會出現在右邊的data 而且可以搜尋

print(vectorExample)
print(listExample)
```

每個元素值可以是不同type的物件值
```{r}
#用vector儲存
c("2020-03-31T13:40:55Z",
  "一芳",
  "2",
  "水果茶"
  )

#用list儲存
library(lubridate)
`小明交易1` <- list(
  ymd_hms("2020-03-31T13:40:55Z"), #DateTime
     "一芳", #character
     2, #numeric
     "水果茶" #character
     )
```

物件值可以是vector形式，也可以list。
```{r}
#用vector
c(
  c("108學年第1學期","高級會計學","高等統計學"), #向量一
 c( "108學年第2學期","食在拉丁美洲") #向量二
    )
#想要把108 1,2學期分開，但用vector形式是沒辦法的
```
用法1
```{r}
#List 含兩個 vectors
`小明108學年課表A`<- list(
  c("108學年第1學期","高級會計學","高等統計學"), #向量一
 c( "108學年第2學期","食在拉丁美洲") #向量二
    )
#用list則可以分成atomic vector 1&2 ，但其實裡面的內容不變
```
用法2
```{r}
# list含兩個lists
`小明108學年課表B` <- list(
  list("108-1","高級會計學","高等統計學"),
  list("108-2","食在拉丁美洲")
)
print(`小明108學年課表B`)
```
用法3
```{r}
# list含兩個lists, 子層list又各含兩個vectors
`小明108學年課表C` <- list(
  list(
    c("108-1"), # 可只寫 "108-1"
    c("高級會計學","高等統計學")
       ),
  list(
    c("108-2"),
    c("食在拉丁美洲")
  )
)
print(`小明108學年課表C`)
```

物件值可以取名。
```{r}
`小明108學年課表D` <- list(
  `上學期`=list(
    semester=c("108-1"), 
    courses=c("高級會計學","高等統計學")
       ),
  `下學期`=list(
    semester=c("108-2"),
    courses=c("食在拉丁美洲")
  )
)
print(`小明108學年課表D`)
```

##Github Commit
```{r}
commit <- list(
  author = list(
    name="Martin老師",
    email="mtlin@gm.ntpu.edu.tw",
    time=ymd_hms("2020-03-25T07:17:40Z")),
  commiter = list(
    name="emilyluckey",
    email="emily007@gmail.com",
    time=ymd_hms("2020-03-26T08:18:40Z")),
  message = "update"
)
print(commit)
```

```{r}
browseURL("https://api.github.com/repos/tpemartin/108-2-56-inclass-practice/commits") 
```

```{r}
library(jsonlite) # 不少同學這行會有Error，還記得如何排除嗎？
toJSON(commit)
```

```{r}
`小明修課紀錄`<- list(
  `108-1` = list(
   list(
     name= "個體經濟學",
    teacher= "Alice",
    score=85)),
  list(
    name="總體經濟學",
       teacher="Mark",
       score=73),
  `108-2`= list(
    name="作業研究",
    teacher="Jason",
    score="90")
)
print(`小明修課紀錄`)  

```

```{r}
library(lubridate)
TaipeiCity <- list(
  date= list(
    today= ymd("2020-03-31"),
    tomorrow= ymd("2020-04-01")),
  MaxT = 25,
  minT = 18)

NewTaipeiCity <- list(
  date= list(
    today=ymd("2020-03-31"),
    tomorrow=ymd("2020-04-01")),
  MaxT=24,
  minT=15)

print(TaipeiCity)
print(NewTaipeiCity)
```


























