---
title: "0418practice"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#新增/替換/刪除元素

元素提取[.],[[.]],$.也可用來進行元素「值」的修改與新增

**範例**
```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在: 替換
a[[4]] <- "7" # 元素不存在： 增加
a[c(5,6)] <- c("J", "K")
a
```

```{r}
a[[7]] <- "Johnson"
a

a <- c(a,"Mary") #使用前一章的向量疊代(recursive vector concatenate)法
#也就是用a他自己 再加一個新的元素Mary來產生新的a
a
```


```{r}
library(lubridate)
list1 <- 
  list(
    list(
      name="Jack",
      birthday=ymd("1998-03-21"),
      status=c(height=177, weight=80)
    )
  )

str(list1)
```

```{r}
# 更改日期
list1[[1]]$birthday <- ymd("1997-03-21")

# 新增資料
list1[[2]] <- list(
  name="Mary",
  birthday=ymd("1998-08-24")
)

str(list1)
```

練習:替Mary依Jack的記錄方式增加身高163，體重45
```{r}
list1[[2]]$status <- c(height=163,weight=45)
list1[[1]]$status[["height"]] <- 176
list1
```

母層若為list，則需用list(...)方式增加。

母層若為atomic vector，則用c(...)方式增加

```{r}
list1[[1]][["age"]] <- 21
list1[[2]]["age"] <- list(21)

# 改變「一個」時，使用[[ ]]比較不會錯。
str(list1)
```

```{r}
list1[[1]][c("bloodType","registered")] <- list("AB",TRUE)

str(list1)
```

練習2:

```{r}
listExample <- 
  list(
    student="小明",
    course_info=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )
# 有多少位置可選：
length(listExample)

str(listExample)
```

108-1新增一個“產業經濟學”。
產業經濟學，同時加上教師Wen及成績88。

```{r}
listExample[[2]]$`108-1`[[2]] <- list(name="產業經濟學")
str(listExample)
```

```{r}
listExample[[2]]$`108-1`[[2]][c("teacher","grade")] <- list("Wen",88)
str(listExample)
```

##刪除可以使用[- c(數字位置)]

*只能「一個」中括號（[[.]]不能接受負數值）*

*只能用負數值，不能用元素名稱。*
```{r}
print(a)
a[-c(1,3)]
a[c(-2)] #刪掉第二個元素

print(a)
a[-c(1,3)] -> a # 要回存才算真的刪除
a
```

練習

```{r}
library(lubridate)
list1 <- 
  list(
    list(
      name="Jack",
      birthday=ymd("1998-03-21"),
      status=c(height=177, weight=80)
    ),
    list(
      name="Mary",
      birthday=ymd("1998-08-24"),
      status=c(height=163, weight=45),
      age=21,
      bloodType="AB"
    )
  )
str(list1)
```

*刪除Jack的status.*

```{r}

list1[[1]][-3] -> list1[[1]] # 小心回存的位置

str(list1)
```

*刪除Mary的status, blookType.*
```{r}
list1[[2]][-c(3,5)] -> list1[[2]]
str(list1)
```

list元素要刪除時也可以用 `[.]<-NULL`, `[[.]]<-NULL`
```{r}
str(list1)
list1[[2]][c(1,2)] <- NULL #用null就不用回存
str(list1)
```

練習
```{r}
library(jsonlite)
fromJSON("https://data.ntpc.gov.tw/od/data/api/54DDDC93-589C-4858-9C95-18B2046CC1FC?$format=json", simplifyDataFrame = F) -> newTaipeiYouBike
str(newTaipeiYouBike,max.level = 1)
```

```{r}
newTaipeiYouBike[[2]][c(4,5)] <- NULL
```










